#!/bin/sh

weather=$(curl -s wttr.in?format="4")

icon="|🌎"

printf "%s%s\n" "$icon" "$weather"

# The BLOCK_BUTTON bloat for clicking in dwmblocks.
case $BLOCK_BUTTON in 
    1) getforecast & ;;
    2) notify-send "$(curl wttr.in/{BanskáBystrica,Assenovgrad,Plovdiv,Krakow,Varna}?format=4)" ;;
    3) notify-send "🌈 Weather module" "\- Left click for full forecast.
- Middle click to update forecast." ;;
esac
